apiVersion: v1
kind: Service
metadata:
  name: ${K8S_ENV_SLUG}-app-${K8S_PROJECT}
  namespace: ${K8S_NS}
  labels:
    env: ${K8S_ENV_SLUG}
    app: app
    project: ${K8S_PROJECT}
    tier: backend
spec:
  selector:
    env: ${K8S_ENV_SLUG}
    app: app
    project: ${K8S_PROJECT}
    tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000